name: Update Submodule on Release

on:
    release:
        types:
            - published
            - prereleased
jobs:
    update-submodule:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout target repository
              uses: actions/checkout@v4
              with:
                  repository: icure/the-forge
                  token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
                  ref: master
                  submodules: true
                  fetch-tags: true

            - name: Configure Git
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"

            - name: Update submodule to latest
              run: |
                  git submodule update --remote --recursive kotlin-fhir-model-generator
                  git add kotlin-fhir-model-generator

            - name: Commit if changed
              run: |
                  if ! git diff --cached --quiet; then
                    git commit -m "chore: Update submodule on release ${{ github.event.release.tag_name }}"
                    git tag -a "kotlin-fhir-model-generator-${{ github.event.release.tag_name }}" -m "Update submodule to kotlin-fhir-model-generator version ${{ github.event.release.tag_name }}"
                    git push --follow-tags
                  fi
