//
//  Generated from FHIR Version 4.3.0
//
package io.icure.fhir.mapping.domain.fhir.r4b.subscriptiontopic

import io.icure.fhir.mapping.domain.fhir.r4b.backboneelement.BackboneElement
import io.icure.fhir.mapping.domain.fhir.r4b.extension.Extension
import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Properties for describing the shape of notifications generated by this topic
 *
 * List of properties to describe the shape (e.g., resources) included in notifications from this
 * Subscription Topic.
 *
 * @param id Unique id for inter-element referencing
 * @param resource URL of the Resource that is the focus (main) resource in a notification shape
 */
@SerialName("SubscriptionTopicNotificationShape")
@Serializable
public data class SubscriptionTopicNotificationShape(
  /**
   * Unique id for inter-element referencing
   */
  override val id: String? = null,
  override val extension: List<Extension> = emptyList(),
  override val modifierExtension: List<Extension> = emptyList(),
  /**
   * URL of the Resource that is the focus (main) resource in a notification shape
   */
  public val resource: String? = null,
  public val include: List<String> = emptyList(),
  public val revInclude: List<String> = emptyList(),
) : BackboneElement
